# Generated by Django 4.0.2 on 2022-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Atau')),
                ('full_text', models.TextField(verbose_name='Sipat')),
                ('author', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Traditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Atau')),
                ('intro', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Sipat')),
                ('famous', models.CharField(max_length=40, verbose_name='Name')),
                ('history', models.TextField(verbose_name='Tarih')),
            ],
        ),
    ]
