# Generated by Django 4.0.2 on 2022-03-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0002_foods_traditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Atau')),
                ('full_text', models.TextField(verbose_name='Sipat')),
            ],
        ),
        migrations.RenameModel(
            old_name='Traditions',
            new_name='Tradition',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
