# Generated by Django 4.0.2 on 2022-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0005_remove_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('author', models.CharField(default='anonymous', max_length=30)),
                ('feedback', models.TextField(default='That was amazing!!!')),
            ],
        ),
    ]
