# Generated by Django 4.0.2 on 2022-03-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='place',
            new_name='name',
        ),
    ]
