# Generated by Django 4.0.2 on 2022-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0008_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
