# Generated by Django 4.0.2 on 2022-04-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0010_feedback_age_feedback_email_feedback_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('maleF', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
