# Generated by Django 4.0.2 on 2022-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0011_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(max_length=15),
        ),
    ]
