# Generated by Django 4.0.2 on 2022-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0013_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
