# Generated by Django 3.2.10 on 2022-05-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0015_alter_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='age',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='time',
        ),
    ]
