# Generated by Django 3.2.10 on 2022-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0016_auto_20220502_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradition',
            name='slug',
            field=models.SlugField(default='f', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
