# Generated by Django 3.2.10 on 2022-05-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0017_tradition_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradition',
            name='slug',
        ),
    ]
