# Generated by Django 3.2.10 on 2022-05-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzsport', '0018_remove_tradition_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tradition',
        ),
    ]
